// src/components/DropCell.tsx
// src/components/DropCell.tsx
import { useDroppable } from "@dnd-kit/core";
import type { Subject, RoomsEnroll } from "../types/examPlanner";
import { PlacedChip } from "./PlacedChip";

type DropCellProps = {
  id: string;
  disabled?: boolean;
  assignedList?: Subject[];
  extrasForSubjects?: Record<string, RoomsEnroll>;
  onRemoveOne?: (subjectId: string) => void;
  pid: number;
  dateIso: string;
  slotIndex: number;
};

export function DropCell({
  id,
  disabled,
  assignedList,
  extrasForSubjects,
  onRemoveOne,
  pid,
  dateIso,
  slotIndex,
}: DropCellProps) {
  const { setNodeRef, isOver } = useDroppable({ id, disabled });

  return (
    <td
      ref={setNodeRef}
      className={`align-top min-w-[170px] h-20 p-2 border ${
        disabled
          ? "bg-gray-100 text-gray-400"
          : isOver
          ? "ring-2 ring-indigo-400"
          : "bg-white"
      }`}
    >
      {assignedList && assignedList.length ? (
        <div className="space-y-2">
          {assignedList.map((s) => {
            const extra = extrasForSubjects?.[s.id];

            return (
              <div key={s.id} className="relative">
                {/* Capseta arrossegable entre cel·les, AMB aules/estudiants a dins */}
                <PlacedChip
                  pid={pid}
                  dateIso={dateIso}
                  slotIndex={slotIndex}
                  s={s}
                  extra={extra}
                />

                {!disabled && onRemoveOne && (
                  <button
                    onClick={() => onRemoveOne(s.id)}
                    onPointerDown={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                    }}
                    className="absolute -top-2 -right-2 w-6 h-6 rounded-full border bg-white shadow text-xs"
                    aria-label="Eliminar"
                    title="Eliminar d’aquesta cel·la"
                  >
                    ×
                  </button>
                )}
              </div>
            );
          })}
        </div>
      ) : (
        <div className="text-xs text-gray-400 italic">
          {disabled ? "No disponible" : "Arrossega aquí"}
        </div>
      )}
    </td>
  );
}

// app/components/DropCell.vue
<script setup lang="ts">
import { computed } from 'vue';
import { VueDraggable } from 'vue-draggable-plus';
import type { Subject, RoomsEnroll } from "../types/examPlanner";
import PlacedChip from "./PlacedChip.vue";

const props = defineProps<{
  id: string; // cellKey
  disabled?: boolean;
  assignedList?: Subject[];
  extrasForSubjects?: Record<string, RoomsEnroll>;
  pid: number;
  dateIso: string;
  slotIndex: number;
}>();

const emit = defineEmits<{
  (e: 'remove-one', subjectId: string): void;
  (e: 'update-list', newList: Subject[]): void;
}>();

// Writable computed for v-model
const list = computed({
  get: () => props.assignedList || [],
  set: (val) => {
    emit('update-list', val);
  }
});

function onRemove(subjectId: string) {
  emit('remove-one', subjectId);
}
</script>

<template>
  <td
    class="align-top min-w-[170px] border transition-colors"
    :class="[
      disabled ? 'bg-gray-100 text-gray-400' : 'bg-white'
    ]"
  >
    <ClientOnly>
      <VueDraggable
        v-model="list"
        group="subjects"
        class="space-y-2 min-h-[80px] h-full w-full p-2"
        :disabled="disabled"
        ghost-class="opacity-50"
      >
      <div v-for="s in list" :key="s.id" class="relative group">
        <!-- Capseta arrossegable entre cel·les -->
        <PlacedChip
          :s="s"
          :extra="extrasForSubjects?.[s.id]"
        />

        <button
          v-if="!disabled"
          @click.stop="onRemove(s.id)"
          class="absolute -top-2 -right-2 w-6 h-6 rounded-full border bg-white shadow text-xs flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity hover:bg-red-50"
          aria-label="Eliminar"
          title="Eliminar d'aquesta cel·la"
        >
          ×
        </button>
      </div>

      <div
        v-if="(!list || list.length === 0)"
        class="text-xs text-gray-400 italic pointer-events-none"
      >
        {{ disabled ? "No disponible" : "Arrossega aquí" }}
      </div>
      </VueDraggable>
    </ClientOnly>
  </td>
</template>
