// src/components/PlacedChip.tsx
// src/components/PlacedChip.tsx
import { useDraggable } from "@dnd-kit/core";
import type { Subject, RoomsEnroll } from "../types/examPlanner";
import { MastersLines } from "./MastersLines";

export function PlacedChip({
  pid,
  dateIso,
  slotIndex,
  s,
  extra,
}: {
  pid: number;
  dateIso: string;
  slotIndex: number;
  s: Subject;
  extra?: RoomsEnroll;
}) {
  // id especial per moure entre cel·les
  const dragId = `placed:${pid}:${dateIso}:${slotIndex}:${s.id}`;
  const { attributes, listeners, setNodeRef, transform, isDragging } =
    useDraggable({ id: dragId });

  const hasRooms = extra && extra.rooms && extra.rooms.length > 0;
  const hasStud =
    extra &&
    typeof extra.students === "number" &&
    !Number.isNaN(extra.students);

  return (
    <div
      ref={setNodeRef}
      {...listeners}
      {...attributes}
      className={`relative p-2 rounded-xl border shadow-sm bg-gray-50 ${
        isDragging ? "opacity-70 ring-2 ring-indigo-400" : ""
      }`}
      style={{
        transform: transform
          ? `translate3d(${transform.x}px, ${transform.y}px, 0)`
          : undefined,
      }}
      title="Arrossega per moure a una altra franja"
    >
      <div className="text-sm font-semibold leading-tight">
        {s.sigles} · {s.codi}
      </div>

      {s.nivell ? (
        <div className="text-xs opacity-80">Nivell: {s.nivell}</div>
      ) : (
        <MastersLines s={s} />
      )}

      {(hasRooms || hasStud) && (
        <div className="mt-1 space-y-0.5 text-xs">
          {hasRooms && (
            <div>
              <span className="font-medium">Aules/Rooms:</span>{" "}
              {extra!.rooms.join(", ")}
            </div>
          )}
          {hasStud && (
            <div>
              <span className="font-medium">Estudiants/Students:</span>{" "}
              {extra!.students}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// app/components/PlacedChip.vue
<script setup lang="ts">
import type { Subject, RoomsEnroll } from "../types/examPlanner";
import MastersLines from "./MastersLines.vue";

const props = defineProps<{
  s: Subject;
  extra?: RoomsEnroll;
}>();

const hasRooms = props.extra?.rooms && props.extra.rooms.length > 0;
const hasStud =
  props.extra &&
  typeof props.extra.students === "number" &&
  !Number.isNaN(props.extra.students);
</script>

<template>
  <div
    class="relative p-3 rounded-lg border bg-white dark:bg-grey-10 text-dark dark:text-grey-3 shadow-1 transition-all duration-200 cursor-grab active:cursor-grabbing hover:shadow-4 border-grey-3 dark:border-grey-9 hover:border-primary"
    title="Arrossega per moure a una altra franja"
  >
    <div class="text-sm font-bold leading-tight q-mb-xs text-primary">
      {{ s.sigles }} · {{ s.codi }}
    </div>

    <div v-if="s.nivell" class="text-xs text-grey-7 dark:text-grey-5">
      Nivell: {{ s.nivell }}
    </div>
    <MastersLines v-else :s="s" />

    <div v-if="hasRooms || hasStud" class="q-mt-sm q-pt-xs border-t border-dashed border-grey-3 dark:border-grey-9 space-y-1 text-xs">
      <div v-if="hasRooms" class="flex items-start q-gutter-x-xs no-wrap">
        <q-icon name="room" size="14px" color="primary" class="q-mt-xs" />
        <div class="flex-1">
          <span class="text-weight-bold opacity-70">Aules:</span>
          {{ extra!.rooms.join(", ") }}
        </div>
      </div>
      <div v-if="hasStud" class="flex items-start q-gutter-x-xs no-wrap">
        <q-icon name="groups" size="14px" color="primary" class="q-mt-xs" />
        <div class="flex-1">
          <span class="text-weight-bold opacity-70">Matrícula:</span>
          {{ extra!.students }}
        </div>
      </div>
    </div>
  </div>
</template>
