// src/components/PlacedChip.tsx
// src/components/PlacedChip.tsx
import { useDraggable } from "@dnd-kit/core";
import type { Subject, RoomsEnroll } from "../types/examPlanner";
import { MastersLines } from "./MastersLines";

export function PlacedChip({
  pid,
  dateIso,
  slotIndex,
  s,
  extra,
}: {
  pid: number;
  dateIso: string;
  slotIndex: number;
  s: Subject;
  extra?: RoomsEnroll;
}) {
  // id especial per moure entre cel·les
  const dragId = `placed:${pid}:${dateIso}:${slotIndex}:${s.id}`;
  const { attributes, listeners, setNodeRef, transform, isDragging } =
    useDraggable({ id: dragId });

  const hasRooms = extra && extra.rooms && extra.rooms.length > 0;
  const hasStud =
    extra &&
    typeof extra.students === "number" &&
    !Number.isNaN(extra.students);

  return (
    <div
      ref={setNodeRef}
      {...listeners}
      {...attributes}
      className={`relative p-2 rounded-xl border shadow-sm bg-gray-50 ${
        isDragging ? "opacity-70 ring-2 ring-indigo-400" : ""
      }`}
      style={{
        transform: transform
          ? `translate3d(${transform.x}px, ${transform.y}px, 0)`
          : undefined,
      }}
      title="Arrossega per moure a una altra franja"
    >
      <div className="text-sm font-semibold leading-tight">
        {s.sigles} · {s.codi}
      </div>

      {s.nivell ? (
        <div className="text-xs opacity-80">Nivell: {s.nivell}</div>
      ) : (
        <MastersLines s={s} />
      )}

      {(hasRooms || hasStud) && (
        <div className="mt-1 space-y-0.5 text-xs">
          {hasRooms && (
            <div>
              <span className="font-medium">Aules/Rooms:</span>{" "}
              {extra!.rooms.join(", ")}
            </div>
          )}
          {hasStud && (
            <div>
              <span className="font-medium">Estudiants/Students:</span>{" "}
              {extra!.students}
            </div>
          )}
        </div>
      )}
    </div>
  );
}

// _local_backup_20251201/src/components/PlacedChip.vue
<script setup lang="ts">
import type { Subject, RoomsEnroll } from "../types/examPlanner";
import MastersLines from "./MastersLines.vue";

const props = defineProps<{
  pid: number;
  dateIso: string;
  slotIndex: number;
  s: Subject;
  extra?: RoomsEnroll;
}>();

const hasRooms = props.extra && props.extra.rooms && props.extra.rooms.length > 0;
const hasStud =
  props.extra &&
  typeof props.extra.students === "number" &&
  !Number.isNaN(props.extra.students);

function onDragStart(e: DragEvent) {
  if (e.dataTransfer) {
    const dragId = `placed:${props.pid}:${props.dateIso}:${props.slotIndex}:${props.s.id}`;
    e.dataTransfer.effectAllowed = "move";
    e.dataTransfer.setData("text/plain", dragId);
  }
}
</script>

<template>
  <div
    draggable="true"
    @dragstart="onDragStart"
    class="relative p-2 rounded-xl border shadow-sm bg-gray-50 hover:shadow-md transition-shadow cursor-grab active:cursor-grabbing"
    title="Arrossega per moure a una altra franja"
  >
    <div class="text-sm font-semibold leading-tight">
      {{ s.sigles }} · {{ s.codi }}
    </div>

    <div v-if="s.nivell" class="text-xs opacity-80">
      Nivell: {{ s.nivell }}
    </div>
    <MastersLines v-else :s="s" />

    <div v-if="hasRooms || hasStud" class="mt-1 space-y-0.5 text-xs">
      <div v-if="hasRooms">
        <span class="font-medium">Aules/Rooms:</span>
        {{ extra!.rooms.join(", ") }}
      </div>
      <div v-if="hasStud">
        <span class="font-medium">Estudiants/Students:</span>
        {{ extra!.students }}
      </div>
    </div>
  </div>
</template>
