// app/components/MastersLines.vue
<script setup lang="ts">
import type { Subject } from "../types/examPlanner";

defineProps<{
  s: Subject;
}>();
</script>

<template>
  <div class="flex flex-col text-xs opacity-90 leading-3 mt-0.5">
    <span v-if="s.MET" class="text-grey-7 dark:text-grey-4">MET: {{ s.MET }}</span>
    <span v-if="s.MATT" class="text-blue-700 dark:text-blue-300 font-medium">MATT: {{ s.MATT }}</span>
    <span v-if="s.MEE" class="text-red-700 dark:text-red-300 font-medium">MEE: {{ s.MEE }}</span>
    <span v-if="s.MCYBERS" class="text-green-700 dark:text-green-300 font-medium">MCY: {{ s.MCYBERS }}</span>
  </div>
</template>

// src/components/MastersLines.tsx
// src/components/MastersLines.tsx
import type { Subject } from "../types/examPlanner";

export function MastersLines({ s }: { s: Subject }) {
  const hasAny = s.MET || s.MATT || s.MEE || s.MCYBERS;
  if (!hasAny) return null;

  return (
    <div className="mt-1 text-[10px] leading-tight space-y-0.5">
      {/* MET neutre */}
      {s.MET && (
        <div className="text-gray-600">
          <span>{s.MET}</span>
        </div>
      )}

      {/* MATT en blau */}
      {s.MATT && (
        <div className="text-blue-700">
          <span>{s.MATT}</span>
        </div>
      )}

      {/* MEE en vermell */}
      {s.MEE && (
        <div className="text-red-700">
          <span>{s.MEE}</span>
        </div>
      )}

      {/* MCYBERS en verd */}
      {s.MCYBERS && (
        <div className="text-green-700">
          <span>{s.MCYBERS}</span>
        </div>
      )}
    </div>
  );
}
