// app/components/PlannerToolbar.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Subject, Period } from "../types/examPlanner";
import type { CalendarSummary } from "../types/savedCalendar";
import { importExcelCalendar, type ImportedCalendarData } from "../utils/importExcelCalendar";

const props = defineProps<{
  availableSubjects: Subject[];
  subjects: Subject[];
  lastDeleted: { subject: Subject } | null;
  periods: Period[];
  activePid: number;
  isAdminMode: boolean;

  savedCalendars: CalendarSummary[];
  selectedCalendarId: string;
  selectedTitulacio: string;
  titulacionsDisponibles: string[];
  isTitulacioLocked: boolean;
}>();

const emit = defineEmits<{
  (e: 'undo-delete'): void;
  (e: 'set-last-deleted', val: any): void;
  (e: 'set-active-pid', id: number): void;
  (e: 'add-period'): void;
  (e: 'remove-period', pid: number): void;

  // Import/Export events
  (e: 'import-csv', event: Event): void;
  (e: 'merge-subjects-csv', event: Event): void;
  (e: 'import-rooms-csv', event: Event): void;
  (e: 'import-json', event: Event): void;
  (e: 'import-calendar-data', data: ImportedCalendarData): void;

  (e: 'export-csv'): void;
  (e: 'export-txt'): void;
  (e: 'export-excel'): void;
  (e: 'export-gef-excel'): void;
  (e: 'export-word'): void;
  (e: 'export-json'): void;

  (e: 'save-state'): void;
  (e: 'load-state'): void;
  (e: 'copy-link'): void;

  (e: 'save-supabase'): void;
  (e: 'list-supabase-calendars'): void;
  (e: 'load-latest-supabase-calendar'): void;
  (e: 'load-selected-supabase-calendar', id: string): void;
  (e: 'rename-selected-supabase-calendar'): void;
  (e: 'delete-selected-supabase-calendar'): void;
  (e: 'set-selected-calendar-id', id: string): void;
  (e: 'set-selected-titulacio', value: string): void;
  (e: 'apply-supabase-template'): void;
  (e: 'explain-template-use'): void;

  (e: 'toggle-admin-mode', password?: string): boolean;
}>();

const totalSubjects = props.subjects.length;
const availableCount = props.availableSubjects.length;
const assignedCount = totalSubjects - availableCount;

const showPasswordDialog = ref(false);
const passwordInput = ref("");
const passwordError = ref(false);
const showAdvancedPanel = ref(false);

function getPeriodLabel(p: Period) {
  const tipus = p.tipus === "FINAL" ? "FINAL" : p.tipus === "REAVALUACIÓ" ? "REAVALUACIÓ" : "PARCIAL";
  const curs = p.curs ?? '';
  const quad = p.quad ?? '';

  // Build label: TIPUS CURS-QUADRIMESTRE
  let label = tipus;
  if (curs) {
    label += ` ${curs}`;
    if (quad) {
      label += `-${quad}`;
    }
  } else if (quad) {
    label += ` -${quad}`;
  }

  return label;
}

function attemptUnlock() {
  showPasswordDialog.value = true;
  passwordError.value = false;
  passwordInput.value = "";
}

function submitPassword() {
  const wasLocked = !props.isAdminMode;
  emit('toggle-admin-mode', passwordInput.value);

  // Use nextTick to check if unlock was successful after the parent updates
  setTimeout(() => {
    if (wasLocked && props.isAdminMode) {
      // Successfully unlocked
      showPasswordDialog.value = false;
      passwordInput.value = "";
      passwordError.value = false;
    } else if (wasLocked && !props.isAdminMode) {
      // Failed to unlock (wrong password)
      passwordError.value = true;
    }
  }, 50);
}

function lockAdmin() {
  emit('toggle-admin-mode');
}

function toggleAdvancedPanel() {
  if (!props.isAdminMode) return;
  showAdvancedPanel.value = !showAdvancedPanel.value;
}

function cancelPassword() {
  showPasswordDialog.value = false;
  passwordInput.value = "";
  passwordError.value = false;
}

function handleImportExcel(event: Event) {
  const input = event.target as HTMLInputElement;
  const file = input.files?.[0];
  if (!file) return;

  importExcelCalendar(file, props.subjects)
    .then((data) => {
      emit('import-calendar-data', data);
      alert("Calendari llegit correctament. Actualitzant...");
    })
    .catch((err) => {
      console.error(err);
      alert("Error important el calendari Excel: " + err);
    })
    .finally(() => {
      input.value = "";
    });
}
</script>

<template>
  <div class="p-4  mb-6">
    <div class="flex flex-wrap items-center justify-between gap-3 mb-4">
      <h4 class="text-2xl font-semibold text-primary">Gestió del calendari</h4>

      <div class="flex items-center gap-2">
        <button @click="toggleAdvancedPanel" :disabled="!isAdminMode"
          class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
          :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
          ⚙ Accions avançades
          <span v-if="isAdminMode">
            {{ showAdvancedPanel ? "▲" : "▼" }}
          </span>
        </button>

        <button v-if="!isAdminMode" @click="attemptUnlock"
          class="px-3 py-2 text-sm border rounded-xl bg-yellow-50 hover:bg-yellow-100 border-yellow-300 font-medium">
          🔓 Desbloquejar
        </button>

        <button v-else @click="lockAdmin"
          class="px-3 py-2 text-sm border rounded-xl bg-green-50 hover:bg-green-100 border-green-300 font-medium">
          🔒 Bloquejar
        </button>
      </div>
    </div>

    <div class="space-y-4">
      <div class="border rounded-xl p-3 bg-primary-50">
        <h5 class="text-sm font-semibold text-gray-700 mb-3">
          Calendaris guardats
        </h5>

        <div class="flex flex-wrap gap-3 items-center">
          <select :value="selectedTitulacio" :disabled="props.isTitulacioLocked"
            @change="emit('set-selected-titulacio', ($event.target as HTMLSelectElement).value)"
            class="px-3 py-2 border rounded bg-white min-w-[220px]"
            :class="props.isTitulacioLocked ? 'opacity-60 cursor-not-allowed bg-gray-100' : ''">
            <option value="">Totes les titulacions</option>
            <option v-for="tit in titulacionsDisponibles" :key="tit" :value="tit">
              {{ tit }}
            </option>
          </select>

          <span v-if="props.isTitulacioLocked" class="text-xs text-gray-600">
            Titulació fixada per l'enllaç
          </span>

          <select :value="selectedCalendarId"
            @change="emit('set-selected-calendar-id', ($event.target as HTMLSelectElement).value)"
            class="px-3 py-2 border rounded bg-white min-w-[320px]">
            <option value="">Selecciona un calendari</option>
            <option v-for="cal in savedCalendars" :key="cal.id" :value="cal.id">
              {{ cal.name }}
            </option>
          </select>

          <button @click="emit('load-latest-supabase-calendar')"
            class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
            Carregar últim
          </button>

          <button @click="emit('save-supabase')"
            class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
            Guardar
          </button>

          <button @click="emit('rename-selected-supabase-calendar')"
            class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
            Reanomenar seleccionat
          </button>

          <button @click="emit('delete-selected-supabase-calendar')"
            class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
            Eliminar seleccionat
          </button>

          <button @click="emit('export-excel')" class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
            Exportar calendari en Excel
          </button>

          <button @click="emit('export-word')" class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
            Exportar calendari en Word
          </button>

        </div>
      </div>

      <div v-if="showAdvancedPanel" class="border rounded-xl p-3 bg-gray-50">
        <h3 class="text-sm font-semibold text-gray-700 mb-3">
          ⚙ Accions avançades
        </h3>

        <div class="space-y-4">
          <div class="border rounded-xl p-3 bg-gray-50">
            <h4 class="text-sm font-semibold text-gray-700 mb-3">
              🔒 Administració d'importació i exportació tècnica
            </h4>

            <p class="text-sm text-gray-600 mb-3">
              CSV esperat (assignatures/períodes):
              <code class="bg-gray-100 px-1 rounded">
    codi,sigles,nivell,curs,quadrimestre,period_id,period_tipus,period_inici,period_fi,period_slots,period_blackouts
  </code>
              . Opcional: <code class="bg-gray-100 px-1 rounded">MET,MATT,MEE,MCYBERS</code>.
            </p>

            <div class="flex flex-wrap gap-3 items-center">
              <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Importar CSV (REEMPLAÇA)
                <input type="file" accept=".csv,text/csv" class="hidden" :disabled="!isAdminMode"
                  @change="(e) => emit('import-csv', e)" />
              </label>

              <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Afegir assignatures (CSV) — MERGE
                <input type="file" accept=".csv,text/csv" class="hidden" :disabled="!isAdminMode"
                  @change="(e) => emit('merge-subjects-csv', e)" />
              </label>

              <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Importar Aules/Matriculats (CSV)
                <input type="file" accept=".csv,text/csv" class="hidden" :disabled="!isAdminMode"
                  @change="(e) => emit('import-rooms-csv', e)" />
              </label>

              <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Importar calendari en Excel
                <input type="file" accept=".xlsx, .xls" class="hidden" :disabled="!isAdminMode"
                  @change="handleImportExcel" />
              </label>

              <button @click="emit('export-csv')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Exportar CSV
              </button>

              <button @click="emit('export-txt')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Exportar TXT
              </button>

              <button @click="emit('export-json')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Exportar JSON
              </button>

              <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Importar JSON
                <input type="file" accept="application/json" class="hidden" :disabled="!isAdminMode"
                  @change="(e) => emit('import-json', e)" />
              </label>

              <button @click="emit('save-state')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Guardar estat a l'URL
              </button>

              <button @click="emit('load-state')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Carregar estat de l'URL
              </button>

              <button @click="emit('copy-link')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Copiar enllaç
              </button>

              <button @click="emit('apply-supabase-template')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Aplicar plantilla
              </button>

              <button @click="emit('explain-template-use')" :disabled="!isAdminMode"
                class="px-3 py-2 border rounded-xl shadow-sm transition-colors"
                :class="isAdminMode ? 'bg-white hover:bg-gray-50' : 'bg-gray-200 cursor-not-allowed opacity-60'">
                Com funciona
              </button>

              <button @click="emit('export-gef-excel')"
                class="px-3 py-2 border rounded-xl shadow-sm bg-white hover:bg-gray-50">
                Exportar Excel GEF
              </button>

            </div>
          </div>
        </div>
      </div>
    </div>


    <p class="text-xs text-gray-600 mt-4">
      Assignatures disponibles a la safata:
      <strong>{{ availableCount }}</strong> (de {{ totalSubjects }}). Assignades al
      calendari (tots períodes): <strong>{{ assignedCount }}</strong>.
    </p>

    <div v-if="lastDeleted"
      class="mt-3 p-2 bg-yellow-50 border border-yellow-300 rounded-xl text-xs flex items-center justify-between gap-2">
      <span>
        Assignatura eliminada del catàleg:
        <strong>
          {{ lastDeleted.subject.sigles || lastDeleted.subject.codi }}
        </strong>
      </span>
      <div class="flex gap-2">
        <button @click="emit('undo-delete')" class="px-2 py-1 text-xs border rounded-lg bg-white hover:bg-gray-50">
          Desfer
        </button>
        <button @click="emit('set-last-deleted', null)"
          class="px-2 py-1 text-xs border rounded-lg bg-white hover:bg-gray-50">
          Amaga
        </button>
      </div>
    </div>

    <div class="mt-4 flex flex-wrap items-center gap-3">
      <div class="flex flex-wrap gap-2">
        <button v-for="p in periods" :key="p.id" @click="emit('set-active-pid', p.id)"
          class="px-4 py-2 rounded-full border text-sm font-medium transition-colors" :class="[
            p.id === activePid
              ? 'bg-blue-600 text-white border-blue-700'
              : 'bg-white hover:bg-gray-50'
          ]">
          {{ getPeriodLabel(p) }}
        </button>
      </div>
    </div>

    <div v-if="showPasswordDialog" class="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50"
      @click.self="cancelPassword">
      <div class="bg-white rounded-2xl p-6 shadow-xl max-w-md w-full mx-4">
        <h3 class="text-lg font-semibold mb-4">🔐 Introdueix la contrasenya d'administrador</h3>

        <input v-model="passwordInput" type="password" placeholder="Contrasenya"
          class="w-full border rounded-xl p-3 mb-3" :class="passwordError ? 'border-red-500' : 'border-gray-300'"
          @keyup.enter="submitPassword" autofocus />

        <p v-if="passwordError" class="text-sm text-red-600 mb-3">
          ❌ Contrasenya incorrecta. Torna-ho a intentar.
        </p>

        <div class="flex gap-3 justify-end">
          <button @click="cancelPassword" class="px-4 py-2 border rounded-xl hover:bg-gray-50">
            Cancel·lar
          </button>
          <button @click="submitPassword" class="px-4 py-2 bg-blue-600 text-white rounded-xl hover:bg-blue-700">
            Desbloquejar
          </button>
        </div>
      </div>
    </div>
  </div>
</template>

// src/components/PlannerToolbar.tsx
// src/components/PlannerToolbar.tsx
import type React from "react";
import type { Subject, Period } from "../types/examPlanner";

interface PlannerToolbarProps {
  availableSubjects: Subject[];
  subjects: Subject[];

  lastDeleted: { subject: Subject } | null;
  undoDelete: () => void;
  setLastDeleted: (value: any) => void;

  periods: Period[];
  activePid: number;
  setActivePid: (id: number) => void;
  addPeriod: () => void;
  removePeriod: (pid: number) => void;

  handleImportCSV: React.ChangeEventHandler<HTMLInputElement>;
  handleMergeSubjectsCSV: React.ChangeEventHandler<HTMLInputElement>;
  handleImportRoomsCSV: React.ChangeEventHandler<HTMLInputElement>;

  exportCSV: () => void;
  exportTXT: () => void;
  exportExcel: () => void;
  exportWord: () => void;
  exportJSON: () => void;
  importJSON: React.ChangeEventHandler<HTMLInputElement>;

  saveStateToUrl: () => void;
  loadStateFromUrl: () => boolean;
  copyLinkToClipboard: () => void;
}

export function PlannerToolbar(props: PlannerToolbarProps) {
  const {
    availableSubjects,
    subjects,
    lastDeleted,
    undoDelete,
    setLastDeleted,
    periods,
    activePid,
    setActivePid,
    addPeriod,
    removePeriod,
    handleImportCSV,
    handleMergeSubjectsCSV,
    handleImportRoomsCSV,
    exportCSV,
    exportTXT,
    exportExcel,
    exportWord,
    exportJSON,
    importJSON,
    saveStateToUrl,
    loadStateFromUrl,
    copyLinkToClipboard,
  } = props;

  const totalSubjects = subjects.length;
  const availableCount = availableSubjects.length;
  const assignedCount = totalSubjects - availableCount;

  return (
    <div className="p-4 rounded-2xl border shadow-sm bg-white mb-6">
      <h2 className="font-semibold mb-3">Dades i intercanvi</h2>

      {/* Botons d'import/export i enllaç */}
      <div className="flex flex-wrap gap-3 items-center">
        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Importar CSV (REEMPLAÇA)
          <input
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={handleImportCSV}
          />
        </label>

        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Afegir assignatures (CSV) — MERGE
          <input
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={handleMergeSubjectsCSV}
          />
        </label>

        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Importar Aules/Matriculats (CSV)
          <input
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={handleImportRoomsCSV}
          />
        </label>

        <button
          onClick={exportCSV}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar CSV
        </button>
        <button
          onClick={exportTXT}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar TXT
        </button>
        <button
          onClick={exportExcel}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar Excel
        </button>
        <button
          onClick={exportWord}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar calendari en Word
        </button>
        <button
          onClick={exportJSON}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar JSON
        </button>

        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Importar JSON
          <input
            type="file"
            accept="application/json"
            className="hidden"
            onChange={importJSON}
          />
        </label>

        <button
          onClick={saveStateToUrl}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Guardar estat a l&apos;URL
        </button>
        <button
          onClick={loadStateFromUrl}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Carregar estat de l&apos;URL
        </button>
        <button
          onClick={copyLinkToClipboard}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Copiar enllaç
        </button>
      </div>

      <p className="text-xs text-gray-600 mt-2">
        Assignatures disponibles a la safata:{" "}
        <strong>{availableCount}</strong> (de {totalSubjects}). Assignades al
        calendari (tots períodes): <strong>{assignedCount}</strong>.
      </p>

      <p className="text-xs text-gray-500 mt-1">
        Si canvies molt el CSV, pot ser recomanable reiniciar-ho tot amb
        &nbsp;&quot;Importar CSV (REEMPLAÇA)&quot;.
      </p>

      {/* Banner Desfer eliminació */}
      {lastDeleted && (
        <div className="mt-3 p-2 bg-yellow-50 border border-yellow-300 rounded-xl text-xs flex items-center justify-between gap-2">
          <span>
            Assignatura eliminada del catàleg:{" "}
            <strong>
              {lastDeleted.subject.sigles || lastDeleted.subject.codi}
            </strong>
          </span>
          <div className="flex gap-2">
            <button
              onClick={undoDelete}
              className="px-2 py-1 text-xs border rounded-lg bg-white"
            >
              Desfer
            </button>
            <button
              onClick={() => setLastDeleted(null)}
              className="px-2 py-1 text-xs border rounded-lg bg-white"
            >
              Amaga
            </button>
          </div>
        </div>
      )}

      {/* Pestanyes de períodes – estil xapes grans i text = tipus */}
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <div className="flex flex-wrap gap-2">
          {periods.map((p) => {
            const tipusLabel =
              p.tipus === "FINAL"
                ? "FINAL"
                : p.tipus === "REAVALUACIÓ"
                ? "REAVALUACIÓ"
                : "PARCIAL";

            return (
              <button
                key={p.id}
                onClick={() => setActivePid(p.id)}
                className={`px-4 py-2 rounded-full border text-sm font-medium ${
                  p.id === activePid
                    ? "bg-blue-600 text-white border-blue-700"
                    : "bg-white hover:bg-gray-50"
                }`}
              >
                {tipusLabel}
              </button>
            );
          })}

          <button
            onClick={addPeriod}
            className="px-4 py-2 rounded-full border text-sm bg-green-50 hover:bg-green-100"
          >
            Afegir període
          </button>
        </div>

        {periods.length > 1 && (
          <button
            onClick={() => removePeriod(activePid)}
            className="px-4 py-2 rounded-full border text-sm bg-red-50 hover:bg-red-100"
          >
            Eliminar període actiu
          </button>
        )}
      </div>
    </div>
  );
}
