// src/components/PlannerToolbar.tsx
// src/components/PlannerToolbar.tsx
import type React from "react";
import type { Subject, Period } from "../types/examPlanner";

interface PlannerToolbarProps {
  availableSubjects: Subject[];
  subjects: Subject[];

  lastDeleted: { subject: Subject } | null;
  undoDelete: () => void;
  setLastDeleted: (value: any) => void;

  periods: Period[];
  activePid: number;
  setActivePid: (id: number) => void;
  addPeriod: () => void;
  removePeriod: (pid: number) => void;

  handleImportCSV: React.ChangeEventHandler<HTMLInputElement>;
  handleMergeSubjectsCSV: React.ChangeEventHandler<HTMLInputElement>;
  handleImportRoomsCSV: React.ChangeEventHandler<HTMLInputElement>;

  exportCSV: () => void;
  exportTXT: () => void;
  exportExcel: () => void;
  exportWord: () => void;
  exportJSON: () => void;
  importJSON: React.ChangeEventHandler<HTMLInputElement>;

  saveStateToUrl: () => void;
  loadStateFromUrl: () => boolean;
  copyLinkToClipboard: () => void;
}

export function PlannerToolbar(props: PlannerToolbarProps) {
  const {
    availableSubjects,
    subjects,
    lastDeleted,
    undoDelete,
    setLastDeleted,
    periods,
    activePid,
    setActivePid,
    addPeriod,
    removePeriod,
    handleImportCSV,
    handleMergeSubjectsCSV,
    handleImportRoomsCSV,
    exportCSV,
    exportTXT,
    exportExcel,
    exportWord,
    exportJSON,
    importJSON,
    saveStateToUrl,
    loadStateFromUrl,
    copyLinkToClipboard,
  } = props;

  const totalSubjects = subjects.length;
  const availableCount = availableSubjects.length;
  const assignedCount = totalSubjects - availableCount;

  return (
    <div className="p-4 rounded-2xl border shadow-sm bg-white mb-6">
      <h2 className="font-semibold mb-3">Dades i intercanvi</h2>

      {/* Botons d'import/export i enllaç */}
      <div className="flex flex-wrap gap-3 items-center">
        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Importar CSV (REEMPLAÇA)
          <input
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={handleImportCSV}
          />
        </label>

        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Afegir assignatures (CSV) — MERGE
          <input
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={handleMergeSubjectsCSV}
          />
        </label>

        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Importar Aules/Matriculats (CSV)
          <input
            type="file"
            accept=".csv,text/csv"
            className="hidden"
            onChange={handleImportRoomsCSV}
          />
        </label>

        <button
          onClick={exportCSV}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar CSV
        </button>
        <button
          onClick={exportTXT}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar TXT
        </button>
        <button
          onClick={exportExcel}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar Excel
        </button>
        <button
          onClick={exportWord}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar calendari en Word
        </button>
        <button
          onClick={exportJSON}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Exportar JSON
        </button>

        <label className="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white">
          Importar JSON
          <input
            type="file"
            accept="application/json"
            className="hidden"
            onChange={importJSON}
          />
        </label>

        <button
          onClick={saveStateToUrl}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Guardar estat a l&apos;URL
        </button>
        <button
          onClick={loadStateFromUrl}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Carregar estat de l&apos;URL
        </button>
        <button
          onClick={copyLinkToClipboard}
          className="px-3 py-2 border rounded-xl shadow-sm"
        >
          Copiar enllaç
        </button>
      </div>

      <p className="text-xs text-gray-600 mt-2">
        Assignatures disponibles a la safata:{" "}
        <strong>{availableCount}</strong> (de {totalSubjects}). Assignades al
        calendari (tots períodes): <strong>{assignedCount}</strong>.
      </p>

      <p className="text-xs text-gray-500 mt-1">
        Si canvies molt el CSV, pot ser recomanable reiniciar-ho tot amb
        &nbsp;&quot;Importar CSV (REEMPLAÇA)&quot;.
      </p>

      {/* Banner Desfer eliminació */}
      {lastDeleted && (
        <div className="mt-3 p-2 bg-yellow-50 border border-yellow-300 rounded-xl text-xs flex items-center justify-between gap-2">
          <span>
            Assignatura eliminada del catàleg:{" "}
            <strong>
              {lastDeleted.subject.sigles || lastDeleted.subject.codi}
            </strong>
          </span>
          <div className="flex gap-2">
            <button
              onClick={undoDelete}
              className="px-2 py-1 text-xs border rounded-lg bg-white"
            >
              Desfer
            </button>
            <button
              onClick={() => setLastDeleted(null)}
              className="px-2 py-1 text-xs border rounded-lg bg-white"
            >
              Amaga
            </button>
          </div>
        </div>
      )}

      {/* Pestanyes de períodes – estil xapes grans i text = tipus */}
      <div className="mt-4 flex flex-wrap items-center gap-3">
        <div className="flex flex-wrap gap-2">
          {periods.map((p) => {
            const tipusLabel =
              p.tipus === "FINAL"
                ? "FINAL"
                : p.tipus === "REAVALUACIÓ"
                ? "REAVALUACIÓ"
                : "PARCIAL";

            return (
              <button
                key={p.id}
                onClick={() => setActivePid(p.id)}
                className={`px-4 py-2 rounded-full border text-sm font-medium ${
                  p.id === activePid
                    ? "bg-blue-600 text-white border-blue-700"
                    : "bg-white hover:bg-gray-50"
                }`}
              >
                {tipusLabel}
              </button>
            );
          })}

          <button
            onClick={addPeriod}
            className="px-4 py-2 rounded-full border text-sm bg-green-50 hover:bg-green-100"
          >
            Afegir període
          </button>
        </div>

        {periods.length > 1 && (
          <button
            onClick={() => removePeriod(activePid)}
            className="px-4 py-2 rounded-full border text-sm bg-red-50 hover:bg-red-100"
          >
            Eliminar període actiu
          </button>
        )}
      </div>
    </div>
  );
}

// src/components/PlannerToolbar.vue
<script setup lang="ts">
import type { Subject, Period } from "../types/examPlanner";

const props = defineProps<{
  availableSubjects: Subject[];
  subjects: Subject[];

  lastDeleted: { subject: Subject } | null;
  periods: Period[];
  activePid: number;
}>();

const emit = defineEmits<{
  (e: 'undo-delete'): void;
  (e: 'set-last-deleted', val: any): void;
  (e: 'set-active-pid', id: number): void;
  (e: 'add-period'): void;
  (e: 'remove-period', pid: number): void;

  // Import/Export events
  (e: 'import-csv', event: Event): void;
  (e: 'merge-subjects-csv', event: Event): void;
  (e: 'import-rooms-csv', event: Event): void;
  (e: 'import-json', event: Event): void;
  
  (e: 'export-csv'): void;
  (e: 'export-txt'): void;
  (e: 'export-excel'): void;
  (e: 'export-word'): void;
  (e: 'export-json'): void;

  (e: 'save-state'): void;
  (e: 'load-state'): void;
  (e: 'copy-link'): void;
}>();

const totalSubjects = props.subjects.length;
const availableCount = props.availableSubjects.length;
const assignedCount = totalSubjects - availableCount;

function getTipusLabel(tipus: string) {
  return tipus === "FINAL" ? "FINAL" : tipus === "REAVALUACIÓ" ? "REAVALUACIÓ" : "PARCIAL";
}
</script>

<template>
  <div class="p-4 rounded-2xl border shadow-sm bg-white mb-6">
    <h2 class="font-semibold mb-3">Dades i intercanvi</h2>

    <!-- Botons d'import/export i enllaç -->
    <div class="flex flex-wrap gap-3 items-center">
      <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white hover:bg-gray-50">
        Importar CSV (REEMPLAÇA)
        <input
          type="file"
          accept=".csv,text/csv"
          class="hidden"
          @change="(e) => emit('import-csv', e)"
        />
      </label>

      <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white hover:bg-gray-50">
        Afegir assignatures (CSV) — MERGE
        <input
          type="file"
          accept=".csv,text/csv"
          class="hidden"
          @change="(e) => emit('merge-subjects-csv', e)"
        />
      </label>

      <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white hover:bg-gray-50">
        Importar Aules/Matriculats (CSV)
        <input
          type="file"
          accept=".csv,text/csv"
          class="hidden"
          @change="(e) => emit('import-rooms-csv', e)"
        />
      </label>

      <button @click="emit('export-csv')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Exportar CSV
      </button>
      <button @click="emit('export-txt')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Exportar TXT
      </button>
      <button @click="emit('export-excel')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Exportar calendari en Excel
      </button>
      <button @click="emit('export-word')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Exportar calendari en Word
      </button>
      <button @click="emit('export-json')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Exportar JSON
      </button>

      <label class="px-3 py-2 border rounded-xl shadow-sm cursor-pointer bg-white hover:bg-gray-50">
        Importar JSON
        <input
          type="file"
          accept="application/json"
          class="hidden"
          @change="(e) => emit('import-json', e)"
        />
      </label>

      <button @click="emit('save-state')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Guardar estat a l'URL
      </button>
      <button @click="emit('load-state')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Carregar estat de l'URL
      </button>
      <button @click="emit('copy-link')" class="px-3 py-2 border rounded-xl shadow-sm hover:bg-gray-50">
        Copiar enllaç
      </button>
    </div>

    <p class="text-xs text-gray-600 mt-2">
      Assignatures disponibles a la safata:
      <strong>{{ availableCount }}</strong> (de {{ totalSubjects }}). Assignades al
      calendari (tots períodes): <strong>{{ assignedCount }}</strong>.
    </p>

    <p class="text-xs text-gray-500 mt-1">
      Si canvies molt el CSV, pot ser recomanable reiniciar-ho tot amb
      &nbsp;"Importar CSV (REEMPLAÇA)".
    </p>

    <!-- Banner Desfer eliminació -->
    <div v-if="lastDeleted" class="mt-3 p-2 bg-yellow-50 border border-yellow-300 rounded-xl text-xs flex items-center justify-between gap-2">
      <span>
        Assignatura eliminada del catàleg:
        <strong>
          {{ lastDeleted.subject.sigles || lastDeleted.subject.codi }}
        </strong>
      </span>
      <div class="flex gap-2">
        <button
          @click="emit('undo-delete')"
          class="px-2 py-1 text-xs border rounded-lg bg-white hover:bg-gray-50"
        >
          Desfer
        </button>
        <button
          @click="emit('set-last-deleted', null)"
          class="px-2 py-1 text-xs border rounded-lg bg-white hover:bg-gray-50"
        >
          Amaga
        </button>
      </div>
    </div>

    <!-- Pestanyes de períodes -->
    <div class="mt-4 flex flex-wrap items-center gap-3">
      <div class="flex flex-wrap gap-2">
        <button
          v-for="p in periods"
          :key="p.id"
          @click="emit('set-active-pid', p.id)"
          class="px-4 py-2 rounded-full border text-sm font-medium transition-colors"
          :class="[
            p.id === activePid
              ? 'bg-blue-600 text-white border-blue-700'
              : 'bg-white hover:bg-gray-50'
          ]"
        >
          {{ getTipusLabel(p.tipus) }}
        </button>

        <button
          @click="emit('add-period')"
          class="px-4 py-2 rounded-full border text-sm bg-green-50 hover:bg-green-100 transition-colors"
        >
          Afegir període
        </button>
      </div>

      <button
        v-if="periods.length > 1"
        @click="emit('remove-period', activePid)"
        class="px-4 py-2 rounded-full border text-sm bg-red-50 hover:bg-red-100 transition-colors"
      >
        Eliminar període actiu
      </button>
    </div>
  </div>
</template>
